
spring:
  application:
    name: Meal-Planning
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DATABASE_PSW}
    username: ${DATABASE_USER}
    url: ${DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: none